### ISSUE TITLE
vpc-sample: sample is unused

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-run-samples#148]
The [vpc-sample](https://github.com/GoogleCloudPlatform/cloud-run-samples/tree/main/vpc-sample) was created but the companion tutorial never published.  Should we delete?

**Comment by averikitsch** [comment]
We should connect with iX if there is the ability to quickly finish the tutorial or repurpose this sample.

**Comment by pattishin** [comment]
Merged in CL to incorporate `vpc-sample`. Closing.
