### ISSUE TITLE
Working mTLS gRPC sample for Cloud Run?

### ISSUE THREAD

**Issue by tommed** [GoogleCloudPlatform/cloud-run-samples#15]
My suspicion is that you cannot get mTLS gRPC working in Cloud Run, but if there's a clever way to achieve this, I would be really grateful in seeing it demonstrated?

In our situation, we have our own CA and chain of trust and would like to have mTLS verify both client and server. Most GCP services now allow you to provide your own certificates, but Cloud Run seems to enforce it's own Let's Encrypt cert, even if you configure a hosted gRPC service to use mTLS itself.

Ideally, we'd like to have both server and client using our own certificates (and chain of trust bundles), but a compromise would be to have Cloud Run allow us to validate the client from the server using ClientCAs and ClientAuth fields of `grpc.Creds(credentials.NewTLS(&tls.Config{...}))`.

Example server set-up:

```golang
lis, _ := net.Listen("tcp", addr) // addr uses env:PORT to bind port

// configure TLS client verification
var creds = grpc.Creds(credentials.NewTLS(&tls.Config{
	ClientAuth:    tls.RequireAndVerifyClientCert,
	ClientCAs:     agentBundle,
	Certificates:  []tls.Certificate{serverCert},
	RootCAs:       serverBundle,
}))

// start gRPC service
grpcServer := grpc.NewServer(creds)
RegisterOurServer(grpcServer, impl)
log.Printf("Serving on %s", addr)
return grpcServer.Serve(lis)
```

Can anyone provide a sample for this?

**Comment by grayside** [comment]
Cloud Run doesn't support bring-your-own cert and *.run.app provides a valid TLS server cert. If mTLS authentication is required, you may want to consider if Cloud Run for Anthos would provide the intersection of security and developer experience you need.

**Comment by ahmetb** [comment]
I think the question was more like: how do I provide my own "client cert" as creds in Cloud Run.

The answer is: you can't. Cloud Run doesn't support TLS authentication. (Therefore mTLS cannot be implemented.)

However, deployed Cloud Run apps (HTTPS or gRPC) will provide a valid "server cert" trusted by root CA stores.

**Comment by cavator** [comment]
ok... cool answer.
where is the sample? he ask for a sample.
and i looking for a sample too
