### ISSUE TITLE
Cloud Run Sidecar Won't Update

### ISSUE THREAD

**Issue by HatmanStack** [GoogleCloudPlatform/cloud-run-samples#214]
I was having trouble updating a service I was using to deploy a sidecar container configuration.   The image being built was the same as the image I updated.  I needed to run  

```
gcloud run services add-iam-policy-binding [SERVICE_NAME] \
    --member="allUsers" \
    --role="roles/run.invoker"
```

To update the container policy on every 

`gcloud run services replace service.yaml`

It'd be cool if that was managed.  Keep up the good work!

**Comment by engelke** [comment]
I'm not clear on exactly what you are asking. What does "managed" mean in this context?

**Comment by HatmanStack** [comment]
More a feature request: to only apply the policy-binding once for each service not on every replacement.

**Comment by engelke** [comment]
Feature request has been noted internally
