### ISSUE TITLE
Multi-container runtime issue 

### ISSUE THREAD

**Issue by haposan06** [GoogleCloudPlatform/cloud-run-samples#223]
Hello, 

I followed the tutorial exactly the same as mentioned in https://cloud.google.com/run/docs/internet-proxy-nginx-sidecar
It deployed succesfully, but when I try using cloud run generated link, it gave me this error

`"upstream connect error or disconnect/reset before headers. reset reason: protocol error"`

Edit: Basically I want to achieve this
`https://cloud.google.com/run/docs/internet-proxy-nginx-sidecar#:~:text=translate%20HTTP/2%20to%20HTTP/1%20if%20your%20application%20containers%20supports%20only%20HTTP/1
`
which translates http/2 to http/1. 
When I checked "Use HTTP/2 end-to-end" option, it gave above error. But when I turned it off, it can run normally. 

How does this happen and how to solve it? Thank you

**Comment by pattishin** [comment]
Got it. Thank you for the comment @haposan06 and glad you were able to find what you needed. The tutorial + samples were written for "Use HTTP/2 end-to-end" to not be enabled.
