### ISSUE TITLE
testing(buildcop): add handling for TIMEOUT and INTERNAL_ERROR

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-run-samples#46]
#45 does not address these in it's handling, but these are also error conditions:

* `TIMEOUT`: Something has had a performance regression. We need to know if this happens as more than a flake so we can take steps: 1) Optimize our test, 2) Upgrade the Cloud Build infra, or 3) File a product bug
* `INTERNAL_ERROR`: Cloud Build infra has a problem, not sure what cases surface this kind error but if it happens consistently we need alerting to escalate.

cc @dinagraves

**Comment by dinagraves** [comment]
Can you provide examples of BUILDs that have had these errors?

**Comment by grayside** [comment]
[Viewing build results](https://cloud.google.com/cloud-build/docs/view-build-results#step_status_and_build_status) in the docs covers these. `INTERNAL_ERROR` is not covered there but the full set of status options is [available in the API docs](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#status).

Expanding to review all these states, it seems to me like the following actions make sense:

* `STATUS_UNKNOWN`: Ignore
* `QUEUED`: Ignore
* `WORKING`: Ignore
* `SUCCESS`: Record success
* `FAILURE`: Record failure
* `INTERNAL_ERROR`: Record failure, a significant uptick here requires a product escalation.
* `TIMEOUT`: Record failure, an uptick here might require product escalation or resizing worker.
* `CANCELLED`: Ignore
* `EXPIRED`: =TIMEOUT for our purposes?
